version: 2
updates:
  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/' # location of package.json
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
    ignore:
      # Block all major updates for every package
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

      # For Next.js and React, also block minors (allow only patch)
      - dependency-name: 'next'
        update-types: ['version-update:semver-minor', 'version-update:semver-major']
      - dependency-name: 'react'
        update-types: ['version-update:semver-minor', 'version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-minor', 'version-update:semver-major']
      - dependency-name: '@next/eslint-plugin-next'
        update-types: ['version-update:semver-minor', 'version-update:semver-major']

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github-actions'
    ignore:
      # Block all major updates for GitHub Actions
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
