services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      - NODE_ENV=production
      - APP_ENV=production
      - NEXT_PUBLIC_APP_ENV=production
      - PORT=3000
      - HOSTNAME=localhost
    env_file:
      - .env.production.local
