services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
    environment:
      - NODE_ENV=production
      - APP_ENV=production
      - NEXT_PUBLIC_APP_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.production.local

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
