services:
  frontend_stage:
    container_name: frontend_stage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    restart: always
    environment:
      - NODE_ENV=uat
      - PORT=3030
      - HOSTNAME=localhost
    env_file:
      - .env.local
    networks:
      - my_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
    name: my_network
