services:
  frontend-dev:
    container_name: frontend-template-dev
    build:
      context: .
      dockerfile: Dockerfile.Dev
    restart: on-failure
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - frontend-template
    environment:
      - NODE_ENV=development
      - APP_ENV=development
      - NEXT_PUBLIC_APP_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.local

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  frontend-template:
    driver: bridge
