services:
  frontend-stage:
    container_name: frontend-template-stage
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3030:3030
    networks:
      - frontend-template
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
      - NEXT_PUBLIC_APP_ENV=staging
      - PORT=3030
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.local

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  frontend-template:
    driver: bridge
