services:
  frontend_stage:
    container_name: frontend_stage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    restart: always
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
      - NEXT_PUBLIC_APP_ENV=staging
      - PORT=3030
      - HOSTNAME=localhost
    env_file:
      - .env.staging.local
